/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#24467c",
        "secondary-container": "#63a1ff",
        "tertiary-fixed": "#dfe3e7",
        "background": "#f9f9ff",
        "primary-fixed-dim": "#abc7ff",
        "on-surface": "#111c2c",
        "surface": "#f9f9ff",
        "surface-container": "#e7eeff",
        "primary-container": "#002d62",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary-container": "#7796d1",
        "on-background": "#111c2c",
        "secondary-fixed-dim": "#a9c7ff",
        "on-tertiary-fixed-variant": "#43474b",
        "inverse-on-surface": "#ebf1ff",
        "on-error": "#ffffff",
        "primary-fixed": "#d7e2ff",
        "secondary": "#005db6",
        "inverse-surface": "#263142",
        "surface-container-low": "#f0f3ff",
        "on-tertiary-fixed": "#171c1f",
        "secondary-fixed": "#d6e3ff",
        "on-surface-variant": "#43474f",
        "inverse-primary": "#abc7ff",
        "on-secondary-container": "#00376f",
        "surface-container-high": "#dee8ff",
        "surface-tint": "#3e5e95",
        "surface-dim": "#cfdaf1",
        "tertiary-container": "#2a2f32",
        "primary": "#00193c",
        "surface-bright": "#f9f9ff",
        "outline-variant": "#c4c6d1",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001b3f",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#00468c",
        "tertiary": "#151a1d",
        "on-tertiary-container": "#92969a",
        "tertiary-fixed-dim": "#c3c7cb",
        "outline": "#747781",
        "surface-container-highest": "#d8e3fa",
        "surface-variant": "#d8e3fa",
        "on-secondary-fixed": "#001b3d"
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
        '3xl': '64px',
      },
      fontSize: {
        'h1': ['3rem', { lineHeight: '1.2', fontWeight: '800' }],
        'h2': ['2.25rem', { lineHeight: '1.3', fontWeight: '700' }],
        'h3': ['1.5rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['0.75rem', { lineHeight: '1.5', fontWeight: '700' }],
        'caption': ['0.75rem', { lineHeight: '1.4', fontWeight: '500' }],
      },
      fontFamily: {
        sans: ['"Public Sans"', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
